license="Apache-2.0"
issueTrackerURL="https://github.com/eclipseisoffline/filefixutils/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/eclipseisoffline/filefixutils"
authors="eclipseisoffline"
description='''${mod_description}'''

[[mixins]]
config="filefixutils.mixins.json"

[[mixins]]
config="filefixutils-neoforge.mixins.json"

[[dependencies]]
modId="minecraft"
type="required"
versionRange="${neoforge_minecraft_version}"
ordering="NONE"
side="BOTH"
