license="Apache-2.0"
issueTrackerURL="https://github.com/${github_repository}/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/${github_repository}"
authors="eclipseisoffline"
description='''${mod_description}'''

[[mixins]]
config="filefixutils.mixins.json"

[[dependencies]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_minecraft_version}"
    ordering="NONE"
    side="BOTH"
